# Generated by Django 6.0.5 on 2026-05-17 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_phone', models.CharField(max_length=15)),
                ('test_name', models.CharField(max_length=100)),
                ('verdict', models.TextField(default='Pending')),
                ('is_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
