# Generated by Django 6.0.5 on 2026-05-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='doctor_name',
            field=models.CharField(default='Unassigned', max_length=100),
        ),
    ]
