# Generated by Django 6.0.5 on 2026-05-31 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_patientreport_doctor_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreport',
            name='doctor_name',
        ),
        migrations.RemoveField(
            model_name='patientreport',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='patientreport',
            name='patient_phone',
        ),
        migrations.RemoveField(
            model_name='patientreport',
            name='test_name',
        ),
        migrations.AddField(
            model_name='patientreport',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='patient_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='verdict',
            field=models.TextField(),
        ),
    ]
